export enum ErrorCode {
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  ELEMENT_RATIO_ERROR = 'ELEMENT_RATIO_ERROR',
  PDF_GENERATION_FAILED = 'PDF_GENERATION_FAILED',
  MEDIA_UPLOAD_FAILED = 'MEDIA_UPLOAD_FAILED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}

export const errorStatusMap: Record<ErrorCode, number> = {
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCode.TEMPLATE_NOT_FOUND]: 404,
  [ErrorCode.ELEMENT_RATIO_ERROR]: 400,
  [ErrorCode.PDF_GENERATION_FAILED]: 500,
  [ErrorCode.MEDIA_UPLOAD_FAILED]: 400,
  [ErrorCode.VALIDATION_ERROR]: 400,
};